-- NOTE: Flyway is not currently on the classpath (no flyway dependency in
-- pom.xml), so this file is NOT executed at runtime. Table creation is handled
-- by schema.sql via spring.sql.init.mode=always. This migration is kept in
-- sync with schema.sql (portable H2/PostgreSQL syntax, idempotent) so that
-- enabling Flyway later does not fail against an existing database.
CREATE TABLE IF NOT EXISTS login_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    attempt_type VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_username_timestamp ON login_attempts(username, timestamp);
CREATE INDEX IF NOT EXISTS idx_ip_timestamp ON login_attempts(ip_address, timestamp);
CREATE INDEX IF NOT EXISTS idx_username_ip_timestamp ON login_attempts(username, ip_address, timestamp);
